# -*- coding: utf-8 -*-
"""numbers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmvV4SlGX2739WGZgKEgC-EuNrL093wI

#Numbers
"""

20 + 50

20 - 50

50 - 20

20 / 30

30 / 20

2*7

2**2

2**7

2***2

2/4

2//4

2//168

3//168

5//168

5//9

2%4

2%7

11%4

number = 20 / 30
print(number)
print(round(number,2))
round(number,4)

10+2*4

(10+2)*4

6-5.7

round(6-5.7,2)