# -*- coding: utf-8 -*-
"""strings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahNOE2dReY1DA3gljhgw91K9OhcH-RV8

#Strings
"""

string="good morning"
print(string)

string[0:4]

string[:4]

string[4:12]

string[5:12]

string[5:15]

string[5:]

string[0]=f

string2="hello world"
print(string2)

string2='hello world'
print(string2)

string2='''hello world'''
print(string2)

string2='hello "world"'
print(string2)

s1="total months in a year are"
s2=str(12)
print(s1+" " +s2)