# -*- coding: utf-8 -*-
"""variables

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pDqu6ab1rnbjp_6hEzWm9GQlVjQUt6l

#Variables
"""

month1 = 1000
month2 = 3000
month3 = 5000

total = month1 + month2 + month3
print (total)

print("Total months are:",3,"\nand total expense is:", total)



Dinner = input("What would you like to eat? ")
print("The visitor wants to eat",Dinner)